version: 2
updates:
- target-branch: master
  package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- target-branch: iso5
  package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "inmanta-core"
    - dependency-name: "inmanta-license"
    - dependency-name: "inmanta-lsm"
    - dependency-name: "inmanta-support"
    - dependency-name: "inmanta-ui"