change-type: patch
description: set up dependabot to ignore all extensions on all named iso branches
issue-nr : 274
issue-repo: inmanta-service-orchestrator
destination-branches:
- master
sections: {}
